name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Debug project structure
        run: |
          echo "Current directory:"
          pwd
          echo "Project structure:"
          find . -type f -name "*.ts" | sort
          echo "Package.json:"
          cat package.json
          echo "Index.ts:"
          cat src/index.ts
          echo "TSup config:"
          cat tsup.config.ts

      - name: Build package
        run: npm run build
        
      - name: Check build output
        run: |
          echo "Build output:"
          ls -la dist/
          echo "Index.js:"
          cat dist/index.js | head -n 10
